name: 'Dockerize manager-orders-api'
on:
  push:
    paths:
    - 'manager-orders-api/**'
    - 'buildAll'

jobs:
  build-and-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build native
        run: cd manager-orders-api && ./mvnw -f ../extension-token-machine install && ./mvnw package -Pnative -Dquarkus.native.container-build=true 
      - name: Build docker
        run: cd manager-orders-api && docker build -f src/main/docker/Dockerfile.native -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/manager-orders-api .
      - name: Login to GCP
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Push the Docker image to GCP
        run: |
          gcloud auth configure-docker --quiet
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/manager-orders-api